In [147]:
%matplotlib inline
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import fsspec
from scipy import stats
from scipy.stats import norm, skew
from sklearn import preprocessing
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor, plot_importance
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold

In [152]:
import boto3
bucket='aifa-team-purple' # Or whatever you called your bucket
data_key = 'test_projections/test_data_predictions.csv' # Where the file is within your bucket
data_location = 's3://{}/{}'.format(bucket, data_key)
df = pd.read_csv(data_location)

In [ ]:
df['year'] = df['Open Date'].apply(lambda x: len(df['Open Date']) + str(x) + "'")

In [150]:
df2 = df.drop(columns = "Open Date")
df2 = df2.drop(columns = "Id")
df2 = df2.drop(columns = "Unnamed: 0")

In [151]:
df2

,City,City Group,Type,P1,P2,P3,P4,P5,P6,P7,...,P29,P30,P31,P32,P33,P34,P35,P36,P37,predicted_revenue
0,Ankara,Big Cities,DT,1,3.0,0.0,5.0,5,5,1,...,3.0,0,0,0,0,0,0,0,0,4852964.00
1,İstanbul,Big Cities,FC,5,5.0,4.0,5.0,1,4,5,...,0.0,0,0,0,0,0,0,0,0,9676064.00
2,İstanbul,Big Cities,FC,3,5.0,4.0,4.0,2,5,5,...,2.0,0,0,0,0,0,0,0,0,8749350.00
3,İstanbul,Big Cities,FC,3,5.0,4.0,4.0,2,5,5,...,2.0,0,0,0,0,0,0,0,0,8729628.00
4,İstanbul,Big Cities,FC,3,5.0,4.0,4.0,2,5,5,...,3.0,0,0,0,0,0,0,0,0,7406593.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,Konya,Other,IL,2,2.0,4.0,5.0,4,2,5,...,3.0,0,0,0,0,0,0,0,0,3670620.25
133,Ankara,Big Cities,IL,2,2.0,4.0,4.0,2,1,5,...,3.0,0,0,0,0,0,0,0,0,3617952.25
134,İstanbul,Big Cities,IL,4,5.0,4.0,4.0,2,2,5,...,3.0,0,0,0,0,0,0,0,0,3587020.50
135,Ankara,Big Cities,IL,3,5.0,4.0,5.0,3,4,5,...,3.0,5,2,3,2,2,2,3,3,3566397.00
136,Ankara,Big Cities,IL,3,5.0,4.0,5.0,2,3,5,...,3.0,5,5,4,3,3,4,3,1,3374955.00

In [145]:
print(df2)

         City  City Group Type  P1   P2   P3   P4  P5  P6  P7  ...  P29  P30  \
0      Ankara  Big Cities   DT   1  3.0  0.0  5.0   5   5   1  ...  3.0    0
1    İstanbul  Big Cities   FC   5  5.0  4.0  5.0   1   4   5  ...  0.0    0
2    İstanbul  Big Cities   FC   3  5.0  4.0  4.0   2   5   5  ...  2.0    0
3    İstanbul  Big Cities   FC   3  5.0  4.0  4.0   2   5   5  ...  2.0    0
4    İstanbul  Big Cities   FC   3  5.0  4.0  4.0   2   5   5  ...  3.0    0
..        ...         ...  ...  ..  ...  ...  ...  ..  ..  ..  ...  ...  ...
132     Konya       Other   IL   2  2.0  4.0  5.0   4   2   5  ...  3.0    0
133    Ankara  Big Cities   IL   2  2.0  4.0  4.0   2   1   5  ...  3.0    0
134  İstanbul  Big Cities   IL   4  5.0  4.0  4.0   2   2   5  ...  3.0    0
135    Ankara  Big Cities   IL   3  5.0  4.0  5.0   3   4   5  ...  3.0    5
136    Ankara  Big Cities   IL   3  5.0  4.0  5.0   2   3   5  ...  3.0    5

     P31  P32  P33  P34  P35  P36  P37  predicted_revenue
0      0    0    0    0    0    0    0         4852964.00
1      0    0    0    0    0    0    0         9676064.00
2      0    0    0    0    0    0    0         8749350.00
3      0    0    0    0    0    0    0         8729628.00
4      0    0    0    0    0    0    0         7406593.50
..   ...  ...  ...  ...  ...  ...  ...                ...
132    0    0    0    0    0    0    0         3670620.25
133    0    0    0    0    0    0    0         3617952.25
134    0    0    0    0    0    0    0         3587020.50
135    2    3    2    2    2    3    3         3566397.00
136    5    4    3    3    4    3    1         3374955.00

[137 rows x 41 columns]

In [131]:
y = df2['predicted_revenue']

In [132]:
x= df2.loc[:, df2.columns != 'predicted_revenue']

In [98]:
print(x)

         City  City Group Type  P1   P2   P3   P4  P5  P6  P7  ...  P29  P30  \
0      Ankara  Big Cities   DT   1  3.0  0.0  5.0   5   5   1  ...  3.0    0
1    İstanbul  Big Cities   FC   5  5.0  4.0  5.0   1   4   5  ...  0.0    0
2    İstanbul  Big Cities   FC   3  5.0  4.0  4.0   2   5   5  ...  2.0    0
3    İstanbul  Big Cities   FC   3  5.0  4.0  4.0   2   5   5  ...  2.0    0
4    İstanbul  Big Cities   FC   3  5.0  4.0  4.0   2   5   5  ...  3.0    0
..        ...         ...  ...  ..  ...  ...  ...  ..  ..  ..  ...  ...  ...
132     Konya       Other   IL   2  2.0  4.0  5.0   4   2   5  ...  3.0    0
133    Ankara  Big Cities   IL   2  2.0  4.0  4.0   2   1   5  ...  3.0    0
134  İstanbul  Big Cities   IL   4  5.0  4.0  4.0   2   2   5  ...  3.0    0
135    Ankara  Big Cities   IL   3  5.0  4.0  5.0   3   4   5  ...  3.0    5
136    Ankara  Big Cities   IL   3  5.0  4.0  5.0   2   3   5  ...  3.0    5

     P31  P32  P33  P34  P35  P36  P37  year
0      0    0    0    0    0    0    0  2005
1      0    0    0    0    0    0    0  2005
2      0    0    0    0    0    0    0  2000
3      0    0    0    0    0    0    0  2011
4      0    0    0    0    0    0    0  2000
..   ...  ...  ...  ...  ...  ...  ...   ...
132    0    0    0    0    0    0    0  2011
133    0    0    0    0    0    0    0  2013
134    0    0    0    0    0    0    0  2013
135    2    3    2    2    2    3    3  2010
136    5    4    3    3    4    3    1  2010

[137 rows x 41 columns]

In [133]:
 regr = linear_model.LinearRegression()

In [140]:
x2 = pd.get_dummies(data=x, drop_first=True)

In [136]:
        regr.fit(x2, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [137]:
x_year_2 = x

In [102]:
pd.options.mode.chained_assignment = None  # default='warn'

In [138]:
x_year_2["year"] = pd.to_numeric(x_year_2["year"])
x_year_2["year"] = x_year_2["year"] + 1

KeyError: 'year'

In [139]:
print(x_year_2)

     P1   P2   P3   P4  P5  P6  P7  P8  P9  P10  ...  year_2009  year_2010  \
0     1  3.0  0.0  5.0   5   5   1   5   5    5  ...          0          0
1     5  5.0  4.0  5.0   1   4   5   3   4    4  ...          0          0
2     3  5.0  4.0  4.0   2   5   5   4   5    4  ...          0          0
3     3  5.0  4.0  4.0   2   5   5   4   5    4  ...          0          0
4     3  5.0  4.0  4.0   2   5   5   4   5    4  ...          0          0
..   ..  ...  ...  ...  ..  ..  ..  ..  ..  ...  ...        ...        ...
132   2  2.0  4.0  5.0   4   2   5   5   5    5  ...          0          0
133   2  2.0  4.0  4.0   2   1   5   4   5    5  ...          0          0
134   4  5.0  4.0  4.0   2   2   5   4   4    4  ...          0          0
135   3  5.0  4.0  5.0   3   4   5   4   4    4  ...          0          1
136   3  5.0  4.0  5.0   2   3   5   3   5    4  ...          0          1

     year_2011  year_2012  year_2013  year_2014  year_2096  year_2097  \
0            0          0          0          0          0          0
1            0          0          0          0          0          0
2            0          0          0          0          0          0
3            1          0          0          0          0          0
4            0          0          0          0          0          0
..         ...        ...        ...        ...        ...        ...
132          1          0          0          0          0          0
133          0          0          1          0          0          0
134          0          0          1          0          0          0
135          0          0          0          0          0          0
136          0          0          0          0          0          0

     year_2098  year_2099
0            0          0
1            0          0
2            0          0
3            0          0
4            0          0
..         ...        ...
132          0          0
133          0          0
134          0          0
135          0          0
136          0          0

[137 rows x 89 columns]

In [106]:
x_year_3 = x
x_year_3['year'] = pd.to_numeric(x_year_3['year'])
x_year_3['year'] += 2

In [107]:
x_year_4 = x
x_year_4['year'] = pd.to_numeric(x_year_4['year'])
x_year_4['year'] += 3

In [108]:
x_year_5 = x
x_year_5['year'] = pd.to_numeric(x_year_5['year'])
x_year_5['year'] += 4

In [109]:
print(x_year_5)

         City  City Group Type  P1   P2   P3   P4  P5  P6  P7  ...  P29  P30  \
0      Ankara  Big Cities   DT   1  3.0  0.0  5.0   5   5   1  ...  3.0    0
1    İstanbul  Big Cities   FC   5  5.0  4.0  5.0   1   4   5  ...  0.0    0
2    İstanbul  Big Cities   FC   3  5.0  4.0  4.0   2   5   5  ...  2.0    0
3    İstanbul  Big Cities   FC   3  5.0  4.0  4.0   2   5   5  ...  2.0    0
4    İstanbul  Big Cities   FC   3  5.0  4.0  4.0   2   5   5  ...  3.0    0
..        ...         ...  ...  ..  ...  ...  ...  ..  ..  ..  ...  ...  ...
132     Konya       Other   IL   2  2.0  4.0  5.0   4   2   5  ...  3.0    0
133    Ankara  Big Cities   IL   2  2.0  4.0  4.0   2   1   5  ...  3.0    0
134  İstanbul  Big Cities   IL   4  5.0  4.0  4.0   2   2   5  ...  3.0    0
135    Ankara  Big Cities   IL   3  5.0  4.0  5.0   3   4   5  ...  3.0    5
136    Ankara  Big Cities   IL   3  5.0  4.0  5.0   2   3   5  ...  3.0    5

     P31  P32  P33  P34  P35  P36  P37  year
0      0    0    0    0    0    0    0  2016
1      0    0    0    0    0    0    0  2016
2      0    0    0    0    0    0    0  2011
3      0    0    0    0    0    0    0  2022
4      0    0    0    0    0    0    0  2011
..   ...  ...  ...  ...  ...  ...  ...   ...
132    0    0    0    0    0    0    0  2022
133    0    0    0    0    0    0    0  2024
134    0    0    0    0    0    0    0  2024
135    2    3    2    2    2    3    3  2021
136    5    4    3    3    4    3    1  2021

[137 rows x 41 columns]

In [121]:
x_projections = x_year_2.append(x_year_3).append(x_year_4).append(x_year_5)

In [122]:
print(x_projections)

         City  City Group Type  P1   P2   P3   P4  P5  P6  P7  ...  P29  P30  \
0      Ankara  Big Cities   DT   1  3.0  0.0  5.0   5   5   1  ...  3.0    0
1    İstanbul  Big Cities   FC   5  5.0  4.0  5.0   1   4   5  ...  0.0    0
2    İstanbul  Big Cities   FC   3  5.0  4.0  4.0   2   5   5  ...  2.0    0
3    İstanbul  Big Cities   FC   3  5.0  4.0  4.0   2   5   5  ...  2.0    0
4    İstanbul  Big Cities   FC   3  5.0  4.0  4.0   2   5   5  ...  3.0    0
..        ...         ...  ...  ..  ...  ...  ...  ..  ..  ..  ...  ...  ...
132     Konya       Other   IL   2  2.0  4.0  5.0   4   2   5  ...  3.0    0
133    Ankara  Big Cities   IL   2  2.0  4.0  4.0   2   1   5  ...  3.0    0
134  İstanbul  Big Cities   IL   4  5.0  4.0  4.0   2   2   5  ...  3.0    0
135    Ankara  Big Cities   IL   3  5.0  4.0  5.0   3   4   5  ...  3.0    5
136    Ankara  Big Cities   IL   3  5.0  4.0  5.0   2   3   5  ...  3.0    5

     P31  P32  P33  P34  P35  P36  P37  year
0      0    0    0    0    0    0    0  2016
1      0    0    0    0    0    0    0  2016
2      0    0    0    0    0    0    0  2011
3      0    0    0    0    0    0    0  2022
4      0    0    0    0    0    0    0  2011
..   ...  ...  ...  ...  ...  ...  ...   ...
132    0    0    0    0    0    0    0  2022
133    0    0    0    0    0    0    0  2024
134    0    0    0    0    0    0    0  2024
135    2    3    2    2    2    3    3  2021
136    5    4    3    3    4    3    1  2021

[548 rows x 41 columns]

In [126]:
x_model_projections = pd.get_dummies(data=x_projections, drop_first=True)

In [127]:
    predicted = regr.predict(x_projections)

ValueError: could not convert string to float: 'Ankara'

In [119]:
forecasts  = x_projections
forecasts['projected_revenue'] =  predicted

In [120]:
print(forecasts)

     P1   P2   P3   P4  P5  P6  P7  P8  P9  P10  ...  City_Tokat  \
0     1  3.0  0.0  5.0   5   5   1   5   5    5  ...           0
1     5  5.0  4.0  5.0   1   4   5   3   4    4  ...           0
2     3  5.0  4.0  4.0   2   5   5   4   5    4  ...           0
3     3  5.0  4.0  4.0   2   5   5   4   5    4  ...           0
4     3  5.0  4.0  4.0   2   5   5   4   5    4  ...           0
..   ..  ...  ...  ...  ..  ..  ..  ..  ..  ...  ...         ...
132   2  2.0  4.0  5.0   4   2   5   5   5    5  ...           0
133   2  2.0  4.0  4.0   2   1   5   4   5    5  ...           0
134   4  5.0  4.0  4.0   2   2   5   4   4    4  ...           0
135   3  5.0  4.0  5.0   3   4   5   4   4    4  ...           0
136   3  5.0  4.0  5.0   2   3   5   3   5    4  ...           0

     City_Trabzon  City_Uşak  City_İstanbul  City_İzmir  City_Şanlıurfa  \
0               0          0              0           0               0
1               0          0              1           0               0
2               0          0              1           0               0
3               0          0              1           0               0
4               0          0              1           0               0
..            ...        ...            ...         ...             ...
132             0          0              0           0               0
133             0          0              0           0               0
134             0          0              1           0               0
135             0          0              0           0               0
136             0          0              0           0               0

     City Group_Other  Type_FC  Type_IL  projected_revenue
0                   0        0        0       4.852964e+06
1                   0        1        0       7.514208e+06
2                   0        1        0       6.900873e+06
3                   0        1        0       6.904782e+06
4                   0        1        0       6.975620e+06
..                ...      ...      ...                ...
132                 1        0        1       3.228202e+06
133                 0        0        1       2.865335e+06
134                 0        0        1       4.486210e+06
135                 0        0        1       3.857359e+06
136                 0        0        1       4.432837e+06

[548 rows x 75 columns]